In [1]:
import pandas as pd

In [18]:
df = pd.read_csv('data/F-F_Research_Data_Factors_daily_CSV.zip', compression = 'zip', skiprows = 3, index_col=0)

In [19]:
df.head()

          Mkt-RF   SMB   HML    RF
19260701    0.09 -0.25 -0.27  0.01
19260702    0.45 -0.33 -0.06  0.01
19260706    0.17  0.30 -0.39  0.01
19260707    0.09 -0.58  0.02  0.01
19260708    0.22 -0.38  0.19  0.01

In [20]:
df = df.iloc[:-1, :]

In [21]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [22]:
X

          Mkt-RF   SMB   HML
19260701    0.09 -0.25 -0.27
19260702    0.45 -0.33 -0.06
19260706    0.17  0.30 -0.39
19260707    0.09 -0.58  0.02
19260708    0.22 -0.38  0.19
...          ...   ...   ...
20250825   -0.48 -0.63  0.45
20250826    0.43  0.25  0.13
20250827    0.24  0.40  0.27
20250828    0.35 -0.15 -0.52
20250829   -0.68  0.02  0.85

[26066 rows x 3 columns]

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
ffm = LinearRegression().fit(X, y)

In [25]:
ffm.coef_

array([-0.00021935, -0.00025967,  0.00015257])

In [26]:
ffm.intercept_

0.011922950396327797